monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-audio-technica_AT2020USB.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 100
        priority.driver  = 100
      }
    }
  }
]
