unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf reloaded"

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB:usstyle:hyperlinks"
set -as terminal-features ",*256col*:RGB"

set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g detach-on-destroy off
set -g focus-events on
set -g escape-time 10
set -g history-limit 50000

unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind ] copy-mode \; send-keys ?

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r m resize-pane -Z

bind C-l switch-client -l

set-option -g update-environment "EDITOR LANG WAYLAND_DISPLAY XDG_RUNTIME_DIR HYPRLAND_INSTANCE_SIGNATURE DISPLAY SSH_AUTH_SOCK"

run '~/.config/tmux/plugins/tpm/tpm'
