#!/usr/bin/env bash

# base directories to search
base_dirs=("$HOME/Development/DECODE/" "$HOME/Development/Personal/")

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${base_dirs[@]}" -mindepth 1 -maxdepth 1 -type d | awk -F'/' '{print $(NF-2)"/"$NF}' | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_full=$(find "${base_dirs[@]}" -mindepth 1 -maxdepth 1 -type d | awk -F'/' -v selected="$selected" '$(NF-2)"/"$NF == selected {print $0}')

if [[ -z $selected_full ]]; then
    echo "Error: Could not resolve full path for selected directory."
    exit 1
fi

selected_name=$(basename "$selected_full" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected_full"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c "$selected_full"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
